Fix: Extend dayjs calendar plugin
This PR adds the missing extension for the calendar plugin in dayjs inside the datetime-picker.tsx file.
Without this, calling dayjs(currentDate).calendar(calendar) results in a runtime TypeError: calendar is not a function.

Extending the plugin fixes the crash, especially after Expo Prebuild or in native Dev Client setups where dayjs plugins must be manually extended.

Thank you for your awesome work on this package! 🙌